DROP TABLE DONACIONES CASCADE CONSTRAINT;
CREATE TABLE DONACIONES (
    CODIGO_DONACION NUMBER(10) CONSTRAINT donacion_pk PRIMARY KEY,
    TIPO VARCHAR2(15) NOT NULL,
  VOLUMEN NUMBER(10) NOT NULL,
     FECHA DATE NOT NULL,
    ULTIMA_DONACION DATE NOT NULL);

DROP TABLE DONANTES CASCADE CONSTRAINT;
CREATE TABLE DONANTES (
    NUM_DONANTES NUMBER(10) CONSTRAINT donantes_pk PRIMARY KEY,
    NOMBRE VARCHAR2(20) NOT NULL,
    APELLIDO1 VARCHAR2(20) NOT NULL,
    APELLIDO2 VARCHAR2(20) NOT NULL,
    DNI VARCHAR2(14) NOT NULL,
    APTITUD VARCHAR2(15) NOT NULL,
    FECHA_NACIMIENTO DATE NOT NULL,
    FOTO VARCHAR2(5) NULL,
    TELEFONO NUMBER(10) NOT NULL,
    TELEFONO_MOVIL NUMBER(10) NOT NULL,
    TIPO_SANGUINEO VARCHAR2(10) NOT NULL,
    PAIS_NACIMIENTO VARCHAR2(20) NOT NULL,
    EMAIL VARCHAR2(35) NOT NULL,
    CP NUMBER(6) NOT NULL,
    PROVINCIA VARCHAR2(20) NOT NULL,
    POBLACION VARCHAR2(20) NOT NULL,
    RESIDENCIA VARCHAR2(20) NOT NULL,
     DIRECCION VARCHAR2(30) NOT NULL,
    SEXO VARCHAR2(15) NOT NULL);

DROP TABLE FORMULARIO CASCADE CONSTRAINT;
CREATE TABLE FORMULARIO (
    CODIGO_FORMULARIO NUMBER(10) CONSTRAINT codigo_pk PRIMARY KEY,
    FECHA DATE NOT NULL,
    FECHA_EXCLUSION DATE NOT NULL,
    ESTADO_DONACION VARCHAR2(20) NOT NULL,
    P1 VARCHAR2(2) NOT NULL,
    P2 VARCHAR2(2) NOT NULL,
    P3 VARCHAR2(2) NOT NULL,
    P4 VARCHAR2(2) NOT NULL,
    P5 VARCHAR2(2) NOT NULL,
    P6 VARCHAR2(2) NOT NULL,
    P7 VARCHAR2(2) NOT NULL,
    P8 VARCHAR2(2) NOT NULL,
    P9 VARCHAR2(2) NOT NULL,
    P10 VARCHAR2(2) NOT NULL,
    P11 VARCHAR2(2) NOT NULL,
    P12 VARCHAR2(2) NOT NULL,
    P13 VARCHAR2(2) NOT NULL,
    P14 VARCHAR2(2) NOT NULL,
    P15 VARCHAR2(2) NOT NULL,
    P16 VARCHAR2(2) NOT NULL,
    P17 VARCHAR2(2) NOT NULL,
    P18 VARCHAR2(2) NOT NULL,
    P19 VARCHAR2(2) NOT NULL,
    P20 VARCHAR2(2) NOT NULL,
    P21 VARCHAR2(2) NOT NULL,
    P22 VARCHAR2(2) NOT NULL,
    P23 VARCHAR2(2) NOT NULL,
    P24 VARCHAR2(2) NOT NULL,
    P25 VARCHAR2(2) NOT NULL,
    P26 VARCHAR2(2) NOT NULL,
    P27 VARCHAR2(2) NOT NULL,
    P28 VARCHAR2(2) NOT NULL,
    P29 VARCHAR2(2) NOT NULL,
    P30 VARCHAR2(2) NOT NULL,
    P31 VARCHAR2(2) NOT NULL,
P_EXCLUSION1 VARCHAR2(2) NOT NULL,
   P_EXCLUSION2 VARCHAR2(2) NOT NULL,
    P_EXCLUSION3 VARCHAR2(2) NOT NULL);

DROP TABLE REALIZAN CASCADE CONSTRAINT;
CREATE TABLE REALIZAN (
    CODIGO_DONACION NUMBER(10),
    NUM_DONANTES NUMBER(10),
    CONSTRAINT realiza_pk PRIMARY KEY (CODIGO_DONACION, NUM_DONANTES),
    CONSTRAINT realiza_fk1 FOREIGN KEY (CODIGO_DONACION) REFERENCES DONACIONES (CODIGO_DONACION) ON DELETE CASCADE,
     CONSTRAINT realiza_fk2 FOREIGN KEY (NUM_DONANTES) REFERENCES DONANTES (NUM_DONANTES) ON DELETE CASCADE);

DROP TABLE RELLENA CASCADE CONSTRAINT;
CREATE TABLE RELLENA (
    NUM_DONANTES NUMBER(10) NOT NULL,
    CODIGO_FORMULARIO NUMBER(10) NOT NULL,
    CONSTRAINT rellena_pk PRIMARY KEY (NUM_DONANTES, CODIGO_FORMULARIO),
    CONSTRAINT rellena_fk1 FOREIGN KEY (NUM_DONANTES) REFERENCES DONANTES (NUM_DONANTES) ON DELETE CASCADE,
    CONSTRAINT rellena_fk2 FOREIGN KEY (CODIGO_FORMULARIO) REFERENCES FORMULARIO (CODIGO_FORMULARIO) ON DELETE CASCADE);
    
    
    
    
    
    
    